import { MigrationInterface, QueryRunner, Table, TableIndex, TableUnique } from 'typeorm';

export class CountryInitialSchema1747700580149 implements MigrationInterface {
  name = 'CountryInitialSchema1747700580149';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'country',
        columns: [
          {
            name: 'id',
            type: 'uuid',
            isPrimary: true,
            isGenerated: true,
            generationStrategy: 'uuid',
            default: 'uuid_generate_v4()',
          },
          {
            name: 'country_name_en',
            type: 'varchar',
            length: '100',
            isNullable: false,
            comment: '국가명 (영문)',
          },
          {
            name: 'country_name_kr',
            type: 'varchar',
            length: '100',
            isNullable: false,
            comment: '국가명 (한글)',
          },
          {
            name: 'country_calling_code',
            type: 'varchar',
            length: '10',
            isNullable: false,
            comment: '국제 전화 코드',
          },
          {
            name: 'country_code',
            type: 'varchar',
            length: '2',
            isNullable: false,
            comment: '국가 코드 (ISO 3166-1 alpha-2)',
          },
          {
            name: 'currency_code',
            type: 'varchar',
            length: '3',
            isNullable: false,
            comment: '통화 코드 (ISO 4217)',
          },
        ],
      }),
      true,
    );

    await queryRunner.createIndex(
      'country',
      new TableIndex({
        name: 'idx_country_calling_code_a',
        columnNames: ['country_calling_code'],
      }),
    );

    await queryRunner.createUniqueConstraint(
      'country',
      new TableUnique({
        name: 'uq_country_name_en_a',
        columnNames: ['country_name_en'],
      }),
    );

    await queryRunner.createUniqueConstraint(
      'country',
      new TableUnique({
        name: 'uq_country_name_kr_a',
        columnNames: ['country_name_kr'],
      }),
    );

    await queryRunner.query(`
      INSERT INTO country (country_name_en, country_name_kr, country_calling_code, country_code, currency_code) VALUES
      ('Andorra', '안도라', '376', 'AD', 'EUR'),
      ('Afghanistan', '아프가니스탄', '93', 'AF', 'AFN'),
      ('Antigua and Barbuda', '안티가 바부다', '1268', 'AG', 'XCD'),
      ('Anguilla', '앵귈라', '1264', 'AI', 'XCD'),
      ('Albania', '알바니아', '355', 'AL', 'ALL'),
      ('Armenia', '아르메니아', '374', 'AM', 'AMD'),
      ('Angola', '앙골라', '244', 'AO', 'AOA'),
      ('Antarctica', '남극', '672', 'AQ', ''),
      ('Argentina', '아르헨티나', '54', 'AR', 'ARS'),
      ('American Samoa', '아메리칸 사모아', '1684', 'AS', 'USD'),
      ('Austria', '오스트리아', '43', 'AT', 'EUR'),
      ('Australia', '오스트레일리아', '61', 'AU', 'AUD'),
      ('Aruba', '아루바', '297', 'AW', 'AWG'),
      ('Åland Islands', '알란드', '358', 'AX', 'EUR'),
      ('Azerbaijan', '아제르바이잔', '994', 'AZ', 'AZN'),
      ('Bosnia and Herzegovina', '보스니아 헤르체고비나', '387', 'BA', 'BAM'),
      ('Barbados', '바베이도스', '1246', 'BB', 'BBD'),
      ('Bangladesh', '방글라데시', '880', 'BD', 'BDT'),
      ('Belgium', '벨기에', '32', 'BE', 'EUR'),
      ('Burkina Faso', '부르키나 파소', '226', 'BF', 'XOF'),
      ('Bulgaria', '불가리아', '359', 'BG', 'BGN'),
      ('Bahrain', '바레인', '973', 'BH', 'BHD'),
      ('Burundi', '부룬디', '257', 'BI', 'BIF'),
      ('Benin', '베냉', '229', 'BJ', 'XOF'),
      ('Saint Barthélemy', '생바르텔레미', '590', 'BL', 'EUR'),
      ('Bermuda', '버뮤다', '1441', 'BM', 'BMD'),
      ('Brunei Darussalam', '브루나이', '673', 'BN', 'BND'),
      ('Bolivia (Plurinational State of)', '볼리비아', '591', 'BO', 'BOP'),
      ('Bonaire, Sint Eustatius and Saba', '카리비안 네덜란드', '5997', 'BQ', 'USD'),
      ('Brazil', '브라질', '55', 'BR', 'BRL'),
      ('Bhutan', '부탄', '975', 'BT', 'BTN'),
      ('Bouvet Island', '부베 섬', '47', 'BV', 'NOK'),
      ('Botswana', '보츠와나', '267', 'BW', 'BWP'),
      ('Belarus', '벨라루스', '375', 'BY', 'BYR'),
      ('Belize', '벨리즈', '501', 'BZ', 'BZD'),
      ('Canada', '캐나다', '1', 'CA', 'CAD'),
      ('Switzerland', '스위스', '41', 'CH', 'CHF'),
      ('Côte d''Ivoire', '코트디부아르', '225', 'CI', 'XOF'),
      ('Chile', '칠리', '56', 'CL', 'CLP'),
      ('Cameroon', '카메룬', '237', 'CM', 'XAF'),
      ('China', '중국', '86', 'CN', 'CNY'),
      ('Colombia', '콜롬비아', '57', 'CO', 'COP'),
      ('Costa Rica', '코스타리카', '506', 'CR', 'CRC'),
      ('Cuba', '쿠바', '53', 'CU', 'CUC'),
      ('Cabo Verde', '카보베르데', '238', 'CV', 'CVE'),
      ('Curaçao', '쿠라소', '599', 'CW', 'ANG'),
      ('Christmas Island', '크리스마스 섬', '61', 'CX', 'AUD'),
      ('Cyprus', '키프로스', '357', 'CY', 'EUR'),
      ('Germany', '독일', '49', 'DE', 'EUR'),
      ('Djibouti', '지부티', '253', 'DJ', 'DJF'),
      ('Denmark', '덴마크', '45', 'DK', 'DKK'),
      ('Dominica', '도미니카', '767', 'DM', 'XCD'),
      ('Algeria', '알제리', '213', 'DZ', 'DZD'),
      ('Ecuador', '에콰도르', '593', 'EC', 'USD'),
      ('Estonia', '에스토니아', '372', 'EE', 'EUR'),
      ('Egypt', '이집트', '20', 'EG', 'EGP'),
      ('Western Sahara', '서사하라 서부', '212', 'EH', 'MAD'),
      ('Eritrea', '에리트리아', '291', 'ER', 'ERN'),
      ('Spain', '스페인', '34', 'ES', 'EUR'),
      ('Ethiopia', '에티오피아', '251', 'ET', 'ETB'),
      ('Finland', '핀란드', '358', 'FI', 'EUR'),
      ('Fiji', '피지', '679', 'FJ', 'FJD'),
      ('Micronesia (Federated States of)', '미크로네시아 연방', '691', 'FM', 'USD'),
      ('France', '프랑스', '33', 'FR', 'EUR'),
      ('Gabon', '가봉', '241', 'GA', 'XAF'),
      ('Grenada', '그레나다', '1473', 'GD', 'XCD'),
      ('Georgia', '조지아', '995', 'GE', 'GEL'),
      ('French Guiana', '프랑스 기아나', '594', 'GF', 'EUR'),
      ('Guernsey', '건시', '44', 'GG', 'GBP'),
      ('Ghana', '가나', '233', 'GH', 'GHS'),
      ('Gibraltar', '지브롤터', '350', 'GI', 'GIP'),
      ('Greenland', '그린란드', '299', 'GL', 'DKK'),
      ('Guinea', '기니', '224', 'GN', 'GNF'),
      ('Guadeloupe', '과들루프', '590', 'GP', 'EUR'),
      ('Equatorial Guinea', '기니 적도 기니', '240', 'GQ', 'XAF'),
      ('Greece', '그리스', '30', 'GR', 'EUR'),
      ('South Georgia and the South Sandwich Islands', '남지지아 남샌드위치 제도', '500', 'GS', ''),
      ('Guatemala', '과테말라', '502', 'GT', 'GTQ'),
      ('Guam', '괌', '1', 'GU', 'USD'),
      ('Guinea-Bissau', '기니비사우', '245', 'GW', 'XOF'),
      ('Guyana', '가이아나', '592', 'GY', 'GYD'),
      ('Hong Kong', '홍콩', '852', 'HK', 'HKD'),
      ('Honduras', '온드라스', '504', 'HN', 'HNL'),
      ('Croatia', '크로아티아', '385', 'HR', 'HRK'),
      ('Haiti', '하이티', '509', 'HT', 'HTG'),
      ('Hungary', '헝가리', '36', 'HU', 'HUF'),
      ('Indonesia', '인도네시아', '62', 'ID', 'IDR'),
      ('Ireland', '아일랜드', '353', 'IE', 'EUR'),
      ('Israel', '이스라엘', '972', 'IL', 'ILS'),
      ('Isle of Man', '맨섬', '44', 'IM', 'GBP'),
      ('India', '인도', '91', 'IN', 'INR'),
      ('Iraq', '이라크', '964', 'IQ', 'IQD'),
      ('Iran (Islamic Republic of)', '이란', '98', 'IR', 'IRR'),
      ('Iceland', '아이슬란드', '354', 'IS', 'ISK'),
      ('Italy', '이탈리아', '39', 'IT', 'EUR'),
      ('Jersey', '저지', '44', 'JE', 'GBP'),
      ('Jamaica', '자메이카', '876', 'JM', 'JMD'),
      ('Jordan', '요르단', '962', 'JO', 'JOD'),
      ('Japan', '일본', '81', 'JP', 'JPY'),
      ('Kenya', '케냐', '254', 'KE', 'KES'),
      ('Kyrgyzstan', '키르기스스탄', '996', 'KG', 'KGS'),
      ('Cambodia', '캄보디아', '855', 'KH', 'KHR'),
      ('North Korea', '조선민주주의인민공화국', '850', 'KP', 'KPW'),
      ('South Korea', '대한민국', '82', 'KR', 'KRW'),
      ('Kiribati', '키리바시', '686', 'KI', 'AUD'),
      ('Saint Kitts and Nevis', '성키츠 앤 네비스', '1869', 'KN', 'XCD'),
      ('Kuwait', '쿠웨이트', '965', 'KW', 'KWD'),
      ('Kazakhstan', '카자흐스탄', '7', 'KZ', 'KZT'),
      ('Lebanon', '레바논', '961', 'LB', 'LBP'),
      ('Saint Lucia', '성 루시아', '1758', 'LC', 'XCD'),
      ('Liechtenstein', '리히텐슈타인', '423', 'LI', 'CHF'),
      ('Sri Lanka', '스리랑카', '94', 'LK', 'LKR'),
      ('Liberia', '라이베리아', '231', 'LR', 'LRD'),
      ('Lesotho', '레소토', '266', 'LS', 'LSL'),
      ('Lithuania', '리투아니아', '370', 'LT', 'EUR'),
      ('Luxembourg', '룩셈부르크', '352', 'LU', 'EUR'),
      ('Latvia', '라트비아', '371', 'LV', 'EUR'),
      ('Libya', '리비아', '218', 'LY', 'LYD'),
      ('Morocco', '모로코', '212', 'MA', 'MAD'),
      ('Monaco', '모나코', '377', 'MC', 'EUR'),
      ('Montenegro', '몬테네그로', '382', 'ME', 'EUR'),
      ('Saint Martin (French part)', '생마르티니크 프랑스 부분', '590', 'MF', 'EUR'),
      ('Madagascar', '마다가스카르', '261', 'MG', 'MGA'),
      ('Mali', '말리', '223', 'ML', 'XOF'),
      ('Myanmar', '미얀마', '95', 'MM', 'MMK'),
      ('Mongolia', '몽골', '976', 'MN', 'MNT'),
      ('Macao', '마카오', '853', 'MO', 'MOP'),
      ('Martinique', '마티니크', '596', 'MQ', 'EUR'),
      ('Mauritania', '모리타니아', '222', 'MR', 'MRU'),
      ('Montserrat', '몬트세랫', '1664', 'MS', 'XCD'),
      ('Malta', '몰타', '356', 'MT', 'EUR'),
      ('Mauritius', '모리셔스', '230', 'MU', 'MUR'),
      ('Maldives', '몰디브', '960', 'MV', 'MVR'),
      ('Malawi', '말라위', '265', 'MW', 'MWK'),
      ('Mexico', '멕시코', '52', 'MX', 'MXN'),
      ('Malaysia', '말레이시아', '60', 'MY', 'MYR'),
      ('Mozambique', '모잠비크', '258', 'MZ', 'MZN'),
      ('Namibia', '나미비아', '264', 'NA', 'NAD'),
      ('New Caledonia', '뉴칼레도니아', '687', 'NC', 'XPF'),
      ('Norfolk Island', '노퍽 섬', '672', 'NF', 'AUD'),
      ('Nigeria', '나이지리아', '234', 'NG', 'NGN'),
      ('Nicaragua', '니카라과', '505', 'NI', 'NIO'),
      ('Norway', '노르웨이', '47', 'NO', 'NOK'),
      ('Nepal', '네팔', '977', 'NP', 'NPR'),
      ('Nauru', '나우루', '674', 'NR', 'AUD'),
      ('Niue', '니우에', '683', 'NU', 'NZD'),
      ('New Zealand', '뉴질랜드', '64', 'NZ', 'NZD'),
      ('Oman', '오만', '968', 'OM', 'OMR'),
      ('Panama', '파나마', '507', 'PA', 'PAB'),
      ('Peru', '페루', '51', 'PE', 'PEN'),
      ('French Polynesia', '프랑스령 폴리네시아', '689', 'PF', 'XPF'),
      ('Papua New Guinea', '파푸아뉴기니', '675', 'PG', 'PGK'),
      ('Pakistan', '파키스탄', '92', 'PK', 'PKR'),
      ('Poland', '폴란드', '48', 'PL', 'PLN'),
      ('Saint Pierre and Miquelon', '생피에르 앤 미켈론', '508', 'PM', 'EUR'),
      ('Pitcairn', '피카르디아 섬', '64', 'PN', 'NZD'),
      ('Puerto Rico', '푸에르토리코', '1', 'PR', 'USD'),
      ('Palestine, State of', '팔레스타인', '970', 'PS', ''),
      ('Portugal', '포르투갈', '351', 'PT', 'EUR'),
      ('Palau', '팔라우', '680', 'PW', 'USD'),
      ('Paraguay', '파라과이', '595', 'PY', 'PYG'),
      ('Qatar', '카타르', '974', 'QA', 'QAR'),
      ('Réunion', '라 리옹', '262', 'RE', 'EUR'),
      ('Romania', '루마니아', '40', 'RO', 'RON'),
      ('Serbia', '세르비아', '381', 'RS', 'RSD'),
      ('Russia', '러시아', '7', 'RU', 'RUB'),
      ('Rwanda', '르완다', '250', 'RW', 'RWF'),
      ('Saudi Arabia', '사우디아라비아', '966', 'SA', 'SAR'),
      ('Solomon Islands', '솔로몬 제도', '677', 'SB', 'SBD'),
      ('Seychelles', '세이셸', '248', 'SC', 'SCR'),
      ('Sweden', '스웨덴', '46', 'SE', 'SEK'),
      ('Singapore', '싱가포르', '65', 'SG', 'SGD'),
      ('Saint Helena, Ascension and Tristan da Cunha', '세인트헬레나 어센션 트리스탄다쿠냐', '290', 'SH', 'SHP'),
      ('Slovenia', '슬로베니아', '386', 'SI', 'EUR'),
      ('Svalbard and Jan Mayen', '스발바르드 앤 얀 마이언', '4779', 'SJ', 'NOK'),
      ('Slovakia', '슬로바키아', '421', 'SK', 'EUR'),
      ('Sierra Leone', '시에라리온', '232', 'SL', 'SLL'),
      ('Republic of San Marino', '산마리노', '378', 'SM', 'EUR'),
      ('Senegal', '세네갈', '221', 'SN', 'XOF'),
      ('Somalia', '소말리아', '252', 'SO', 'SOS'),
      ('Suriname', '수리남', '597', 'SR', 'SRD'),
      ('South Sudan', '남수단', '211', 'SS', 'SSP'),
      ('Sao Tome and Principe', '상투메 프린시페', '239', 'ST', 'STN'),
      ('El Salvador', '엘살바도르', '503', 'SV', 'SVC'),
      ('Sint Maarten (Dutch part)', '신트마르턴', '1721', 'SX', 'ANG'),
      ('Syrian Arab Republic', '시리아', '963', 'SY', 'SYP'),
      ('Chad', '차드', '235', 'TD', 'XAF'),
      ('Togo', '토고', '228', 'TG', 'XOF'),
      ('Thailand', '태국', '66', 'TH', 'THB'),
      ('Tajikistan', '타지키스탄', '992', 'TJ', 'TJS'),
      ('Tokelau', '토켈라우', '690', 'TK', 'NZD'),
      ('Timor-Leste', '동티모르', '670', 'TL', 'USD'),
      ('Turkmenistan', '투르크메니스탄', '993', 'TM', 'TMT'),
      ('Tunisia', '튀니지', '216', 'TN', 'TND'),
      ('Tonga', '통가', '676', 'TO', 'TOP'),
      ('Turkey', '터키', '90', 'TR', 'TRY'),
      ('Trinidad and Tobago', '트리니다드 토바고', '868', 'TT', 'TTD'),
      ('Tuvalu', '투발루', '688', 'TV', 'AUD'),
      ('United Republic of Tanzania', '탄자니아', '255', 'TZ', 'TZS'),
      ('Ukraine', '우크라이나', '380', 'UA', 'UAH'),
      ('Uganda', '우간다', '256', 'UG', 'UGX'),
      ('United States of America', '미국', '1', 'US', 'USD'),
      ('Uruguay', '우루과이', '598', 'UY', 'UYU'),
      ('Uzbekistan', '우즈베키스탄', '998', 'UZ', 'UZS'),
      ('Saint Vincent and the Grenadines', '성비엔티앤 데 그레나딘스', '1784', 'VC', 'XCD'),
      ('Venezuela (Bolivarian Republic of)', '베네수엘라', '58', 'VE', 'VES'),
      ('Virgin Islands (British)', '비진 아일랜드', '1284', 'VG', 'USD'),
      ('Virgin Islands (U.S.)', '미국비진 아일랜드', '1340', 'VI', 'USD'),
      ('Vietnam', '베트남', '84', 'VN', 'VND'),
      ('Vanuatu', '바누아투', '678', 'VU', 'VUV'),
      ('Wallis and Futuna', '월리스 앤 푸툰', '681', 'WF', 'XPF'),
      ('Samoa', '사모아', '685', 'WS', 'WST'),
      ('Yemen', '예멘', '967', 'YE', 'YER'),
      ('Mayotte', '마요트', '262', 'YT', 'EUR'),
      ('South Africa', '남아프리카', '27', 'ZA', 'ZAR'),
      ('Zambia', '잠비아', '260', 'ZM', 'ZMW'),
      ('Zimbabwe', '짐바브웨', '263', 'ZW', 'ZWL'),
      ('Eswatini', '스와질랜드', '268', 'SZ', 'SZL'),
      ('North Macedonia', '마케도니아', '389', 'MK', 'MKD'),
      ('Philippines', '필리핀', '63', 'PH', 'PHP'),
      ('Netherlands', '네덜란드', '31', 'NL', 'EUR'),
      ('United Arab Emirates', '아랍에미리트', '971', 'AE', 'AED'),
      ('Republic of Moldova', '몰도바', '373', 'MD', 'MDL'),
      ('Gambia', '감비아', '220', 'GM', 'GMD'),
      ('Dominican Republic', '도미니카 공화국', '1', 'DO', 'DOP'),
      ('Sudan', '수단', '249', 'SD', 'SDG'),
      ('Lao People''s Democratic Republic', '라오스 인민 민주 공화국', '856', 'LA', 'LAK'),
      ('Taiwan, Province of China', '대만', '886', 'TW', 'TWD'),
      ('Republic of the Congo', '콩고 공화국', '242', 'CG', 'XAF'),
      ('Czechia', '체코', '420', 'CZ', 'CZK'),
      ('United Kingdom', '영국', '44', 'GB', 'GBP'),
      ('Niger', '니제르', '227', 'NE', 'XOF'),
      ('Democratic Republic of the Congo', '콩고 민주 공화국', '243', 'CD', 'CDF'),
      ('Commonwealth of The Bahamas', '바하마 연방', '1 242', 'BS', 'BSD'),
      ('Cocos (Keeling) Islands', '코코스 제도', '61 891', 'CC', 'AUD'),
      ('Central African Republic', '중앙아프리카 공화국', '236', 'CF', 'XAF'),
      ('Cook Islands', '쿡 제도', '682', 'CK', 'NZD'),
      ('Falkland Islands', '포클랜드 제도', '500', 'FK', 'FKP'),
      ('Faroe Islands', '페로 제도', '298', 'FO', 'DKK'),
      ('Territory of Heard Island and McDonald Islands', '허드 맥도널드 제도', '672', 'HM', 'AUD'),
      ('British Indian Ocean Territory', '영국 인도양 지역', '246', 'IO', 'USD'),
      ('Comoros', '코모로', '269', 'KM', 'KMF'),
      ('Cayman Islands', '케이맨 제도', '1 345', 'KY', 'KYD'),
      ('Republic of the Marshall Islands', '마셜 제도', '692', 'MH', 'USD'),
      ('Commonwealth of the Northern Mariana Islands', '북마리아나 제도', '1 670', 'MP', 'USD'),
      ('Turks and Caicos Islands', '터크스 케이커스 제도', '1 649', 'TC', 'USD'),
      ('French Southern and Antarctic Lands', '프랑스 남반구 남극 지역', '672', 'TF', 'EUR'),
      ('United States Minor Outlying Islands', '미국 민속 외령 제도', '1', 'UM', 'USD'),
      ('Holy See', '바티칸', '39', 'VA', 'EUR'),
      ('Republic of Kosovo', '코소보', '383', 'XK', 'EUR'),
      ('Netherlands Antilles', '네덜란드령 안틸레스', '599', 'AN', 'ANG')
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropUniqueConstraint('country', 'uq_country_name_en_a');
    await queryRunner.dropUniqueConstraint('country', 'uq_country_name_kr_a');
    await queryRunner.dropIndex('country', 'idx_country_calling_code_a');
    await queryRunner.dropTable('country');
  }
}
